# Identificadores del proyecto en SonarCloud
sonar.projectKey=HouseLannisterDev_lannister-frontend
sonar.organization=lannisternews

# Nombre y versión visibles en SonarCloud
sonar.projectName=Lannister Frontend
sonar.projectVersion=1.0

# Directorio donde está tu código fuente
sonar.sources=src

# Excluir directorios que no quieras analizar
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Codificación de los archivos fuente
sonar.sourceEncoding=UTF-8
